### ISSUE TITLE
Version 0.3 api TMDB

### ISSUE THREAD

**Issue by NeoLOVix** [NeoLOVix/PSVIstas#1]
Con la versión 0.3 donde ya funciona la conexión a la BBDD, ha dejado de funcionar la búsqueda de pelis y series a través de la api TMDB.

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "AWT-EventQueue-0" info.movito.themoviedbapi.tools.MovieDbException: Failed to read configuration
        at info.movito.themoviedbapi.TmdbApi.<init>(TmdbApi.java:58)
        at info.movito.themoviedbapi.TmdbApi.<init>(TmdbApi.java:44)
        at ddr.pelisseries.vista.GUIBuscarPeli.jButtonBuscarPeliActionPerformed(GUIBuscarPeli.java:176)`

**Comment by NeoLOVix** [comment]
Para la primera parte, referente a 
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.` se añade la dependencia en el pom.xml siguiente:
        `
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
                <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.36</version>`

**Comment by NeoLOVix** [comment]
Para solventar la segunda parte del error, faltaban por introducir las dependencias siguientes en pom.xml

`        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.10.0</version>
            <scope>runtime</scope>
        </dependency>
        
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.10.0</version>
</dependency>

<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.10.0</version>
</dependency>

<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.10.0</version>
</dependency>

<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.12.0</version>
</dependency>`

Una vez se introducen estas dependencias, vuelve a funcionar la búsqueda de películas y series correctamente.
